/**
 * Application error codes — single dictionary for API + tests.
 */
export const ErrorCode = {
  OK: "OK",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  AUTH_UNAUTHORIZED: "AUTH_UNAUTHORIZED",
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  BOOKING_SLOT_CONFLICT: "BOOKING_SLOT_CONFLICT",
  ITEM_UNAVAILABLE: "ITEM_UNAVAILABLE",
  BUSINESS_RULE_VIOLATION: "BUSINESS_RULE_VIOLATION",
  IDEMPOTENCY_CONFLICT: "IDEMPOTENCY_CONFLICT",
  PAYMENT_TIMEOUT: "PAYMENT_TIMEOUT",
  PAYMENT_WEBHOOK_DUPLICATE: "PAYMENT_WEBHOOK_DUPLICATE",
  DISPUTE_INVALID_STATE: "DISPUTE_INVALID_STATE",
  SETTLEMENT_RETRY_EXHAUSTED: "SETTLEMENT_RETRY_EXHAUSTED",
  CONTENT_CARD_TARGET_INVALID: "CONTENT_CARD_TARGET_INVALID",
  LOCAL_VERIFICATION_EXPIRED: "LOCAL_VERIFICATION_EXPIRED",
  LOCAL_VERIFICATION_INVALID: "LOCAL_VERIFICATION_INVALID",
  LOCAL_VERIFICATION_LOCKED: "LOCAL_VERIFICATION_LOCKED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
} as const;

export type ErrorCodeValue = (typeof ErrorCode)[keyof typeof ErrorCode];
